"""
Django settings for codepop_backend project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-20c3kbxd-=q$-6^1^i@6u)jklu(js%g87$9sko85kirto!8afv'

# Stripe Configuration
STRIPE_SECRET_KEY = 'TODO: get a new secret stripe key'
STRIPE_PUBLISHABLE_KEY = 'TODO: get a new publishable stripe key'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'backend'
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'codepop_backend.urls'

CORS_ALLOW_ALL_ORIGINS = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'codepop_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'codepop_database',
        'USER': 'postgres',  # Replace with your PostgreSQL username
        'PASSWORD': 'password',  # Replace with your PostgreSQL password
        'HOST': '127.0.0.1',  # Set to 'localhost' or the IP of your database server
        'PORT': '5432', 
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'backend.authentication.P2PJWTAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'EXCEPTION_HANDLER': 'backend.views.custom_exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Asymmetric Key Setup for P2P Authentication
# For production, load these from secure environment variables or a secrets manager.
# THE PRIVATE KEY IS NEVER STORED IN SOURCE CONTROL.
PRIVATE_KEY = os.environ.get('SERVER_PRIVATE_KEY', """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQD0UrFTyrTNuif0
pMrlAAZUOpH43K3VYhGyvSA9/6osWQzdkfhOyrABkebSLAXCjkOODXKVk8j6k2rl
XZa9KpeXTPnPqUXL12oBX0VIY9cgq8klHgsUeOY2n3raMsDvGFi8uofuDC6kJGI3
EN+CrIJuF0jbWv6spk9xmTeXgXVCcMVxeNmx4b1ysMldP3Uy++AWh+cdxWnhcvY/
mUiGhFPcUB5ChTS8sSCDUSbT6ceoWaEDERxxoQHY1JgYsbvx7SUYo2u5XsPxxa29
jPZKjh08y1eIkY76XBjfrrVE326DYRJYA9I6Q/Z4JHH+TgSODCAQCJbnXjlh8rdO
uESYNpqJAgMBAAECggEAJx7dMUXXgMrE6QxAnJL4xcssYlpbeeZJCoNJQq7Jkxjz
JsCKWiYO2+wpDGVrdVqNgJUF+uNTSU60zWMYkX4yEFI3/G3l33IaPCataPOWQln0
oX0tAwB/btGcZzcR43bU2+tLe+yhbzuQKlxeSDB9IJ7ugIkSbEH48ynjAomtD+UU
mhOY0BqGQEXViF+jOmghzJRuSBVe/pYySPR2AmLc4C/1yoSsSOTjQfATpAy2i+HZ
79Yg0XMUDEf3v38coVGPRircuCFwsfBUN+w6G21H84qoK8p/+4mCM6u9ktSGLVRw
CCtkUWyzfXX9oVq5EXvMWLYwbkHAxkNo8RiTEOrtTQKBgQD9apXnlxEJJH4By3Vb
Uffve7o6AubLVRsrtaPQsqq3SSHIIi45jimLHoP14DojjL6lsu4EIR5a7UFG5xtT
4t+MpDPrE1N/HkBqu5FMMExNg75jv8ZApNh+TkT76oQh1fDkXAl65wex9knf0BXu
xM8oK/6masrfNqvdi4BC0oXx0wKBgQD20F+kjufvxVIArLfWpLd+varXsgRybPUS
uukwlnlCNDqbpG5VJ8i5dG5VuratRjLbdbzDegazp3RJAG8FSViSxvy3LmVI9MVx
YspcLuDSP4EyTsJAqdaBskJTw3u6tJyepRpLsWC5lhL+9/qZA3MQ195bbSUZbCxB
HVs2y+DsswKBgEi74M6Zo0AWgzwMo2BUhG7t+iNQVeGiSawf9CagQTNeAB4rAU1v
qijN114ov0cYzFdOpdX1k3rRgdzR1Bwdj8AUGPqtj1d63U5FC4zsh9nvqCOFFWfU
aHbIDDCpvMbhWsSQTgBCcwj3AXkFhmYDgtmq1un42MV8MZPiyCtltSAVAoGARGrY
yG4Q30dshuFaCLcaYpjDHg2r6+hGO03yzFQ6At8li/WV3CcuHjKnTz512yyFdo55
qBpQd0apFn93Rxjg47cjYMgMrZ+kh9zhyZH5Im8WKlLoyDIMU2GNv1iGGOhuLhAI
bQkbjfaLB4DIR9hL8lRUwDVOPnDdB6PSoCr+C78CgYEAxYRjx+B1I4mp07REzIHK
5C0mWqRLokBAmQd1PI7SQc3ieLqtN/9NF3eiIZb47fX8nLCYuDTa14jemwlWaSFH
R6zVN2x6RDBQg7rV/c2Pqxt4IFShdgYvjouO06oiTIyyjlUIJ88ighakefOXZ0Kc
sTFtAH5UXuEcaCGvYh+u7Fk=
-----END PRIVATE KEY-----""")

PUBLIC_KEY = os.environ.get('SERVER_PUBLIC_KEY', """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA9FKxU8q0zbon9KTK5QAG
VDqR+Nyt1WIRsr0gPf+qLFkM3ZH4TsqwAZHm0iwFwo5Djg1ylZPI+pNq5V2WvSqX
l0z5z6lFy9dqAV9FSGPXIKvJJR4LFHjmNp962jLA7xhYvLqH7gwupCRiNxDfgqyC
bhdI21r+rKZPcZk3l4F1QnDFcXjZseG9crDJXT91MvvgFofnHcVp4XL2P5lIhoRT
3FAeQoU0vLEgg1Em0+nHqFmhAxEccaEB2NSYGLG78e0lGKNruV7D8cWtvYz2So4d
PMtXiJGO+lwY3661RN9ug2ESWAPSOkP2eCRx/k4EjgwgEAiW5145YfK3TrhEmDaa
iQIDAQAB
-----END PUBLIC KEY-----""")

SPECTACULAR_SETTINGS = {
    'TITLE': 'CodePop API',
    'DESCRIPTION': 'Comprehensive API for CodePop beverage management and P2P networking.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'RS256',
    'SIGNING_KEY': PRIVATE_KEY,
    'VERIFYING_KEY': PUBLIC_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Inter-server sync ─────────────────────────────────────────────────────────
# The ServerRegistry primary key for this deployed instance.
# Each server must set the LOCAL_SERVER_ID environment variable so the sync
# framework can identify itself when making or receiving inter-server calls.
LOCAL_SERVER_ID = os.environ.get('LOCAL_SERVER_ID', None)

AUTH_USER_MODEL = 'backend.CustomUser'
